### ISSUE TITLE
Scrolling while downloading causes crash

### ISSUE THREAD

**Issue by theknut** [rovo89/XposedInstaller#182]
Scrolling the download versions list while a download is active will cause the UI to crash.

Reproduce:
- open GravityBox in download section
- go to versions list
- click "Download" on latest version
- wait until download starts
- scroll down to the bottom of the list
  -> UI crashes

Please see the [logcat](http://pastebin.com/7VijJEAj) for further information! NullPointerException in line 125.

**Comment by cha25228** [comment]
2

**Comment by badonla65** [comment]
I'm sorry. I don't know.
