### ISSUE TITLE
No notification buttons for sideloaded module

### ISSUE THREAD

**Issue by pylerSM** [rovo89/XposedInstaller#201]
I am just playing with Xposed, developing small module and I have just realized that notification about new/updated sideloaded module (APK from exclipse) do not include notification buttons (Reboot and activate). There is no such buttons for sideloaded modules.

Can you add these buttons, please?

**Comment by pylerSM** [comment]
Last time I have this issue also. Sometimes it is expanded, sometimes not. Probably controlled by Android but anyway, I don't like this behaviour.

In showModulesUpdatedNotification() we do not create expanded notification (NotificationCompat.BigTextStyle()) just like in showNotActivatedNotification.

@rovo89 could we rework it to expanded notification just like you did it in showNotActivatedNotification?

**Comment by rovo89** [comment]
Sorry, no idea what you mean. BigTextStyle just means that we can use different texts for the expanded notification versus the collapsed notifcation. The buttons should be independent of that. Whether they are shown or not is indeed controlled by Android - only the top notification shows the buttons. I don't think we should interfere with that on app-level. If you don't like it, there might be an Xposed module which can always show them.

**Comment by pylerSM** [comment]
Yes, I understand. 
>there might be an Xposed module

Xposed yeah :)
