### ISSUE TITLE
Xposed can not find class

### ISSUE THREAD

**Issue by someonec** [rovo89/XposedInstaller#230]
My Issue is quite strage.

I am working on a Wechat Plugin. The origin app has an extra dex file in it's folder app_dex 

which can be called plugin-dex. The plugin-dex contains some activities and UIs and 

what I want to hook is in the plugin-dex.

when the app package was loaded, Xposed cant find the UI class, but startActivity(myUI Intent) is 

able to launch.

Perhaps the two dex file in the same app are not loaded at one time ,How can I use Xposed to 

solve the problem?

**Comment by 3412566455** [comment]
Excuse me. I'm sorry  to ask you some question about how to hook WeChat Plugin,
this is my code:
XposedHelpers.findAndHookMethod("com.tencent.mm.plugin.scanner.ui.BaseScanUI",paramLoadPackageParam.classLoader, "onPreviewFrame",byte[].class,Camera.class, new XC_MethodHook() {
			@Override
			protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
				super.beforeHookedMethod(param);
				XposedBridge.log("参数1 = " + param.args[0]);  
				XposedBridge.log("参数2 = " + param.args[1]);  
			}
		});
but the xposed log is notify not find this class ,I want to ask how to solve this problem
