### ISSUE TITLE
Installer crashes when attempting to install

### ISSUE THREAD

**Issue by Enkouyami** [rovo89/XposedInstaller#244]
The installer crashes whenever I try to install the framework. This happens on v2.7 and 2.6 (I haven't tried lower versions than that). My phone is a SPH-D710 running Android 4.0.4 on the 3.0.15-SPH-D710.de22-Cl612283 Kernel and it's build number is IMM76I.FL24.

**Comment by mirh** [comment]
I'd gladly report back if this was indeed fixed, but latest [3.1.1](http://www.apkmirror.com/apk/rovo89/xposed-installer/xposed-installer-3-1-1-release/) doesn't offer any way to install Xposed on my 4.0.4 htc explorer.
