### ISSUE TITLE
Can't Install into Meizu MX4 Flyme OS 4.0.4.1C Which based on Android 4.4.2

### ISSUE THREAD

**Issue by robinsonboy** [rovo89/XposedInstaller#255]
Xposed appear red word "There seems to be a known issue ("Aliyun OS")" with your ROM. Installing Xposed might not work or lead to severe problems. Click here for details about the issue."

is it solve ?

**Comment by alooly053** [comment]
بتاريخ 2015/01/08 12:53 م، جاء من "robinsonboy" <notifications@github.com>:

**Comment by rovo89** [comment]
"Click here for details about the issue." -> Did you do that? The FAQ item it is linked to contains everything I can say about this.

**Comment by alooly053** [comment]
Hi rovo89/XposedInstall,

I'd like to add you to my professional network on LinkedIn.

- ali

Confirm that you know ali: https://www.linkedin.com/e/v2?e=0-ijswojor-g4&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=uqYLZN_I&invitationId=6097099231296831488








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ijswojor-g4&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQE7iIEaWU75iwAAAVJ0_kcB49EX9cJrVACltB4q7hL-snWSoSavtJE3IcEFhOjbXDGpiVwVALh3U2FTaF7swtRO5WCaq_ZG0THHuiuB2rjFg7sxwPbZXjNHYrARrUT0YduDZojrSx_eXm-D-8j9nWPGF8E84AmyQywJRBDy6hol26Nka2q4eRKXAnNN3qlWiqf2&eid=0-ijswojor-g4


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ijswojor-g4&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by alooly053** [comment]
ali alshahiny would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-efg0p0-ijy2gaf5-s&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=uqYLZN_I&invitationID=6097099231296831488

View ali alshahiny&#39;s profile: https://www.linkedin.com/e/v2?e=-efg0p0-ijy2gaf5-s&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=uqYLZN_I&invitationID=6097099231296831488

rovo89/XposedInstall,

أرغب في إضافتك إلى شبكتي الاحترافية على LinkedIn.





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-efg0p0-ijy2gaf5-s&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-efg0p0-ijy2gaf5-s&loid=AQHvWQ7N25-SawAAAVKIVtdDjBLX3_5Snpjhj5X6DVOppw8Obt9A2patQvQg92ynif8JX0OgdzfitxXUkbtN_qye_4slx3f1j24sHcCYSrpgjIkt3FHu25JRXScFqJQtpCzinXuzWHTf98E3zloKxOOxVbTfCXKVD_c24iJXz1KAwD9N39bKpe-hmfiw7q0K8DEf

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-efg0p0-ijy2gaf5-s&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
