### ISSUE TITLE
Allow Installation Without Root

### ISSUE THREAD

**Issue by antgiant** [rovo89/XposedInstaller#269]
I would very much like to be able to install Xposed without root, as for a variety of reasons I don't leave my phone rooted. I do however have a custom recovery installed. 

So, all I am asking for is that the Manual Recovery installation not require a rooted phone. Since this is a very simple change I have created a pull request for it (here)[https://github.com/rovo89/XposedInstaller/pull/268]

If you would like me to redo the pull request for the art branch I am happy to do that as well.

**Comment by theknut** [comment]
Have you tested this on your device?

**Comment by antgiant** [comment]
I have not. However, as noted in the pull request @jurben did. In fact he used it to install Xposed. Do you need me to verify on my device as well?

**Comment by rovo89** [comment]
Please keep discussions in one place. The PR is probably suited better for this, so I close this one.
