### ISSUE TITLE
Allow (soft) reboots without confirmation

### ISSUE THREAD

**Issue by pylerSM** [rovo89/XposedInstaller#273]
Now user needs to confirm "Are you sure" dialog. Allow to disable this behaviour.

Sometimes, when developing module, first notification in notification area is about "PC connection" so Xposed "update module" notification is second one and is not expanded. So you need to do restart manually from "Framework" view. Always click on OK button is annoying.

I did it in my custom build, so I can make send pull request with my implementation too, if you agree with this at all, of course.

**Comment by rovo89** [comment]
I don't think this will interesting for more than a handful of users. I don't think it's worth to introduce an option for that.

If the one click is bothering you, you could either expand the notification (long press on it, then pull down) to reveal the buttons, or you just type `adb shell stop;start`.
