### ISSUE TITLE
Xposed and LuaJit memory space conflict

### ISSUE THREAD

**Issue by gerroon** [rovo89/XposedInstaller#277]
Hi

Tried to contact the author of Xprivacy module about the issue and he recommended it might be an issue with the Xposed Module there for I am writing here.

I try to use Koreader on my device and it has been crasing so the KR devs looked into it with my logs and they think that there is a memory space allocation issue due to Xposed or Xprivacy. I am wondering if you could look into it  to seeif this is an Xposed issue or something to do with Luajit and Xposed not liking each other.

The bug listing is here
https://github.com/koreader/koreader/issues/1456

thanks

**Comment by rovo89** [comment]
I don't know how LuaJit works, but this makes sense to me:

> Of course, neither XPrivacy nor LuaJIT should be blamed for this problem. It's just the shortcoming of LuaJIT (limits mcode allocation within the range of 16MB around luajit library, actually the PC-relative branch limitation of ARM instruction) meets with a hacky way to modify behavior of Android application provided by XPosed/XPrivacy. Neither side of they probably could fix this easily.

Xposed doesn't have any influence on the memory location used for modules. Actually, it just creates new ClassLoaders for the APKs and Android decides what to do with it, which involves mapping the .dex file to memory. This has to be done when the device boots, so it's not possible to free up the memory for a single app. Generally, this isn't a problem, but as mentioned in the quoted text, there might be other restrictions. I don't see a chance to work around this in the Xposed framework though.

**Comment by gerroon** [comment]
@rovo89 

Thanks for your time and explanation. I will quote you in the original bug.
