### ISSUE TITLE
greenify root problem

### ISSUE THREAD

**Issue by candyshopping** [rovo89/XposedInstaller#278]
Hi 
I want ur help with this issue cause I had a root for greenify before I get to pay for the other one but now my system cannot allow me to root it and it says that I do not have the root but I do have it what shall I do now

**Comment by GermainZ** [comment]
Ask in the Greenify thread on XDA (or contact Greenify's developers), the Xposed Installer has nothing to do with this.
On Sat, Mar 21, 2015 at 8:07 AM, candyshopping <notifications@github.com> wrote:Hi 
I want ur help with this issue cause I had a root for greenify before I get to pay for the other one but now my system cannot allow me to root it and it says that I do not have the root but I do have it what shall I do now

**Comment by candyshopping** [comment]
I could not any place that helps me

**Comment by candyshopping** [comment]
I could not find any place that helps me

**Comment by candyshopping** [comment]
It aboutXposed Installer cause I cannot do the Installation ın framework

**Comment by candyshopping** [comment]
I want help

**Comment by rovo89** [comment]
GitHub is not the right place for support questions. User banned for posting many useless requests in a short time, thus spamming all the subscribers.
