### ISSUE TITLE
Crash + soft-reboot when trying to install module via Download tab

### ISSUE THREAD

**Issue by IzzySoft** [rovo89/XposedInstaller#286]
While up to now I've always side-loaded modules and then just activated them (followed by a reboot of course), today for the first time I tried the integrated downloader – as I was far from my computer. Download went smooth, but then the device suddenly soft-rebooted. After boot was completed, I've checked that module: it was downloaded, but not installed, so it showed a download button. On pressing that, immediate soft-reboot again. 100% reproducable.

Tried again when back home, to get some logcat – but I get bombed by entries (~1 MB per minute; I can zip and send the logcat by PM if needed). But from watching it run, this is where it started:

~~~
W/System.err(27717): org.apache.http.conn.HttpHostConnectException: Connection to https://by.uservoice.com refused
[ stack trace here ]
E/UV      (27717): org.apache.http.conn.HttpHostConnectException: Connection to https://by.uservoice.com refused
~~~

All messages following that already seem to be initialization stuff (services starting up/being initialized). PID 27717 seems to be Xposed, as a log entry *before* the crash indicates:

~~~
I/Xposed  (27717): Loading package com.intangibleobject.securesettings.plugin
~~~

Some background: Network was enabled in both cases (first mobile, at home WiFi then). The unreachable server should not cause a crash, but that's all I found. Installing the very same APK via `adb install` afterwards went smoothly (notification shows up as expected that I need to activate the module and reboot).

* **Device:** LG P880, running the latest stock ROM (Android 4.1.2)
* **Xposed:** Latest stable version

**Comment by rovo89** [comment]
Yes, please upload the logcat, otherwise I don't see a chance to analyse this issue.

Note: I don't now the URL in the log, and Xposed doesn't have a separate PID, as it's part of every process.

**Comment by IzzySoft** [comment]
@rovo89 Do you have any "private space" to upload it to, so I don't have to check for possible "private data leaks"? File is ~1.1 MB unzipped / 140 kB zipped. I've put it on one of my servers and tried to PM you the URL at XDA, but you've turned PM off (I haven't, just in case).

**Comment by rovo89** [comment]
You can use the contact from on http://repo.xposed.info.

**Comment by IzzySoft** [comment]
Done! Thanks already now :)

**Comment by rovo89** [comment]
```
06-05 19:54:44.757 I/Xposed  (23872): java.lang.NullPointerException
06-05 19:54:44.757 I/Xposed  (23872): 	at pk.qwerty12.alternateapppicker.AlternateAppPicker$1.afterHookedMethod(AlternateAppPicker.java:68)
06-05 19:54:44.757 I/Xposed  (23872): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
06-05 19:54:44.757 I/Xposed  (23872): 	at com.android.internal.app.ResolverActivity.onCreate(Native Method)
06-05 19:54:44.757 I/Xposed  (23872): 	at com.android.internal.app.ResolverActivity.onCreate(ResolverActivity.java:107)
06-05 19:54:44.757 I/Xposed  (23872): 	at android.app.Activity.performCreate(Activity.java:5191)
06-05 19:54:44.757 I/Xposed  (23872): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082)
06-05 19:54:44.757 I/Xposed  (23872): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2037)
06-05 19:54:44.757 I/Xposed  (23872): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2098)
06-05 19:54:44.757 I/Xposed  (23872): 	at android.app.ActivityThread.access$600(ActivityThread.java:138)
06-05 19:54:44.757 I/Xposed  (23872): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204)
06-05 19:54:44.757 I/Xposed  (23872): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-05 19:54:44.757 I/Xposed  (23872): 	at android.os.Looper.loop(Looper.java:137)
06-05 19:54:44.757 I/Xposed  (23872): 	at com.android.server.ServerThread.run(SystemServer.java:996)
06-05 19:54:44.757 I/Xposed  (23872): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
06-05 19:54:44.757 I/Xposed  (23872): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
06-05 19:54:44.757 I/Xposed  (23872): 	at com.android.server.ServerThread.run(Native Method)
06-05 19:54:44.767 W/dalvikvm(23872): threadid=10: thread exiting with uncaught exception (group=0x4100d2a0)
06-05 19:54:44.767 E/AndroidRuntime(23872): *** FATAL EXCEPTION IN SYSTEM PROCESS: android.server.ServerThread
06-05 19:54:44.767 E/AndroidRuntime(23872): java.lang.RuntimeException: Unable to start activity ComponentInfo{android/com.android.internal.app.ResolverActivity}: java.lang.ClassCastException: android.widget.GridView cannot be cast to android.widget.ListView
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2073)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2098)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at android.app.ActivityThread.access$600(ActivityThread.java:138)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at android.os.Looper.loop(Looper.java:137)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at com.android.server.ServerThread.run(SystemServer.java:996)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at com.android.server.ServerThread.run(Native Method)
06-05 19:54:44.767 E/AndroidRuntime(23872): Caused by: java.lang.ClassCastException: android.widget.GridView cannot be cast to android.widget.ListView
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at com.android.internal.app.ResolverActivity.onCreate(ResolverActivity.java:153)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at com.android.internal.app.ResolverActivity.onCreate(Native Method)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at com.android.internal.app.ResolverActivity.onCreate(ResolverActivity.java:107)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at android.app.Activity.performCreate(Activity.java:5191)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2037)
06-05 19:54:44.767 E/AndroidRuntime(23872): 	... 9 more
```

Try disabling the AlternateAppPicker module.

**Comment by IzzySoft** [comment]
Bingo. And sh\*t: I couldn't get *CompleteActionPlus* to work, and this was the fall-back already. Guess I'll have to fall-back once more and live with the DoubleTap module then.

Meanwhile I've [reported that to the AlternateAppPicker dev at XDA](http://forum.xda-developers.com/xposed/modules/mod-alternate-app-picker-kk-t2977468/page2#post61197999) – so if you see no way to fix it from your end (or rather feel it not your responsibility, as the culprit lies in "the other's code" – not being an Android/Java dev, that's hard to tell for me), feel free to close this ticket then.

Oh: looking back, that module was the logical conclusion anyway: Tapping "install" brought up "package installer or verify+install", so it triggered that module – and it would happen in any other place where a choice exists to "complete with". Makes it more likely a job for laguCool then (unless it happens again with DoubleTap as well, and it's some API in Xposed itself causing this – in which case this issue could be re-opened then).

Thanks a lot for your great app and your great support, Rovo! :thumbsup:
