### ISSUE TITLE
Support ARM AArch64(arm64-v8a) architecture systems(XiaoMi Mi4i etc.)

### ISSUE THREAD

**Issue by Vdragon** [rovo89/XposedInstaller#299]
AArch64(arm64-v8a) is the 64-bit ARM CPU architecture that more and more new product uses, please support them.

I wondered if it's possible to reuse the 32-bit binary though...
Thanks in advance!

**Comment by rovo89** [comment]
How does this differ from the already supported arm64 builds? Or are you talking about pre-Lollipop ROMs?

**Comment by Vdragon** [comment]
@rovo89 
> How does this differ from the already supported arm64 builds?
AFAIK AArch64 is same as arm64.  
I don't know what your "arm64 builds" is by the way, I've installed 2.7 experimental1 APK and it says "Xposed is currently not compatible with Android SDK version 21 or your processor architecture(arm64-v8a)" and the "Install/Upgrade" button is grayed-out.

> Or are you talking about pre-Lollipop ROMs?
XiaoMi Mi4i's (MIUI) ROM is based on Android 5.0.2
