### ISSUE TITLE
Phone won't reboot via xposed 

### ISSUE THREAD

**Issue by terrorist96** [rovo89/XposedInstaller#309]
https://github.com/rovo89/Xposed/issues/103

**Comment by DVDAndroid** [comment]
It seems that reboot doesn't work on 64-bit devices.
In [AssetUtil.java](https://github.com/rovo89/XposedInstaller/blob/master/src/de/robv/android/xposed/installer/util/AssetUtil.java#l29) at line 29, ```getBinariesFolder()``` returns null, so when XposedInstaller try to extract busybox, it try to search [(line 95)](https://github.com/rovo89/XposedInstaller/blob/master/src/de/robv/android/xposed/installer/util/AssetUtil.java#l95) in assets/**null**busybox-xposed. This causes the error

**Comment by terrorist96** [comment]
When will a new installer be released so I can test to see if your commit(s) fixed the issue? Thanks.

**Comment by rovo89** [comment]
Sorry, but I don't have time to work on the installer at the moment. I concentrate on the framework instead when I have a bit of time which are , as those issues usually mean that the device cannot start anymore and are therefore more critical. Don't expect new versions of Xposed Installer anytime soon.
