### ISSUE TITLE
Xposed 2.7 not compatible with new Android 4.4.4

### ISSUE THREAD

**Issue by SandPox** [rovo89/XposedInstaller#320]
Look like after Android 4.4.4 receiving security patches it has broke Xposed installer.

![screenshot_2016-01-20-12-29-53](https://cloud.githubusercontent.com/assets/8336751/12440755/f9a8123e-bef3-11e5-9551-20ed31bb52be.png)

**Comment by rovo89** [comment]
Actually it broke the framework, not the installer. See the last paragraph here: http://forum.xda-developers.com/showpost.php?p=64365859&postcount=27
