### ISSUE TITLE
maybe be some bug in Xposed

### ISSUE THREAD

**Issue by l12436** [rovo89/XposedInstaller#325]
there are some stacktrace in logcat. I think is your Xposed's bug.
I'm using HTC butterfly, android 4.4.2
Xposed 2.6.1 XposedBridget.jar 54 appprocess 58

E/ActivityThread(  796): Service com.htc.smartdim.sensor_eye has leaked IntentReceiver com.htc.smartdim.sensor_eye$CoverStateReceiver@43480b58 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(  796): android.app.IntentReceiverLeaked: Service com.htc.smartdim.sensor_eye has leaked IntentReceiver com.htc.smartdim.sensor_eye$CoverStateReceiver@43480b58 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(  796):        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:895)
E/ActivityThread(  796):        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:664)
E/ActivityThread(  796):        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1670)
E/ActivityThread(  796):        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1650)
E/ActivityThread(  796):        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1644)
E/ActivityThread(  796):        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:474)
E/ActivityThread(  796):        at com.htc.smartdim.sensor_eye.register(sensor_eye.java:166)
E/ActivityThread(  796):        at com.htc.smartdim.sensor_eye.onStart(sensor_eye.java:285)
E/ActivityThread(  796):        at android.app.Service.onStartCommand(Service.java:450)
E/ActivityThread(  796):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3187)
E/ActivityThread(  796):        at android.app.ActivityThread.access$2100(ActivityThread.java:156)
E/ActivityThread(  796):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
E/ActivityThread(  796):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread(  796):        at android.os.Looper.loop(Looper.java:157)
E/ActivityThread(  796):        at com.android.server.ServerThread.initAndLoop(SystemServer.java:1430)
E/ActivityThread(  796):        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/ActivityThread(  796):        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
E/ActivityThread(  796):        at com.android.server.ServerThread.initAndLoop(Native Method)
E/ActivityThread(  796):        at com.android.server.SystemServer.main(SystemServer.java:1540)
E/ActivityThread(  796):        at java.lang.reflect.Method.invokeNative(Native Method)
E/ActivityThread(  796):        at java.lang.reflect.Method.invoke(Method.java:515)
E/ActivityThread(  796):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1069)
E/ActivityThread(  796):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
E/ActivityThread(  796):        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/ActivityThread(  796):        at dalvik.system.NativeStart.main(Native Method)

**Comment by rovo89** [comment]
There is no indication that this is caused by Xposed, not sure how you got this idea.

> Service com.htc.smartdim.sensor_eye has leaked IntentReceiver com.htc.smartdim.sensor_eye$CoverStateReceiver@43480b58

Clearly an issue with the HTC app.
