### ISSUE TITLE
Installing zip file ERROR 1

### ISSUE THREAD

**Issue by ulefonebt2** [rovo89/XposedInstaller#336]
i have a Ulefone Be touch 2
recovery twrp 3.2.0.1
modulate rom 2.16 android 5.0

when i try install the file **xposed-v86-sdk21-arm64.zip** in recovery

 appears this message with error:

Installing zip file 'external_sd/exposed-v86-sdk21-arm64.zip'
Cheking for MD5 file...
Skipping MD5 check: no MD5 file found

Xposed framework installer zip

 Mounting /system and /vendor read-write
 Checking enviroment
  Xposed version: 86
 Placing files
gzip: short write
_**Updater process ended with ERROR: 1 Error installing zip file'/external_sd/xposed-v86-sdk21-arm64.zip'**_
Updating partition details...
...done

**Comment by rovo89** [comment]
Your /system partition is probably full.

**Comment by ulefonebt2** [comment]
i try format sd, system, wipe, cache...  all
reinstall only the moderate rom and appears the same ERROR
any idea to solve??
thank you for reply

**Comment by rovo89** [comment]
Please post the TWRP log, it might contain information about the space situation.

**Comment by ulefonebt2** [comment]
when i install exposed.zip appears the error and after the smartphone go in loop on ulefone logo...
now i reflash the rom.. this is the log now

__bionic_open_tzdata: couldn't find any tzdata when looking for localtime!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
Starting TWRP 3.0.2-1 on Wed Aug 10 20:51:12 2016
 (pid 173)
BOARD_HAS_NO_REAL_SDCARD := true
TW_NO_REBOOT_BOOTLOADER := true
RECOVERY_SDCARD_ON_DATA := true
I:Lun file '/sys/devices/msm_dwc3/f9200000.dwc3/gadget/lun0/file' does not exist, USB storage mode disabled
TW_HAS_DOWNLOAD_MODE := true
TW_INCLUDE_CRYPTO := true
I:TW_BRIGHTNESS_PATH := /sys/devices/mdp.0/qcom,mdss_fb_primary.190/leds/lcd-backlight/brightness
I:Specified brightness file '/sys/devices/mdp.0/qcom,mdss_fb_primary.190/leds/lcd-backlight/brightness' not found.
I:Find_File: Error opening '/sys/class/backlight'
I:Found brightness file at '/sys/class/leds/lcd-backlight/brightness'
I:TWFunc::Set_Brightness: Setting brightness control to 162
I:LANG: en
Starting the UI...setting DRM_FORMAT_RGBX8888 and GGL_PIXEL_FORMAT_RGBX_8888
cannot find/open a drm device: No such file or directory
fb0 reports (possibly inaccurate):
  vi.bits_per_pixel = 32
  vi.red.offset   =   0   .length =   8
  vi.green.offset =   8   .length =   8
  vi.blue.offset  =  16   .length =   8
setting GGL_PIXEL_FORMAT_RGBA_8888
double buffered
framebuffer: 0 (1080 x 1920)
ioctl(): blank: Invalid argument
ioctl(): blank: Invalid argument
Using fbdev graphics.
I:TWFunc::Set_Brightness: Setting brightness control to 162
I:Loading package: splash (/twres/splash.xml)
I:Load XML directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/splash.xml' directly
I:Checking resolution...
I:Loading resources...
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Loading page splash
I:Switching packages (splash)
=> Linking mtab
=> Processing recovery.fstab
I:Processing '/boot'
I:Processing '/logo'
I:Processing '/nvram'
I:Processing '/recovery'
I:Processing '/lk'
I:Processing '/proinfo'
I:Processing '/protect_f'
I:Processing '/protect_s'
I:Processing '/system'
I:Processing '/system_image'
I:Processing '/cache'
I:Processing '/data'
I:Unhandled fstab information: 'backup=1;wipeingui;wipeduringfactoryreset', 65, line: '/data		ext4		/dev/block/platform/mtk-msdc.0/by-name/userdata     backup=1;wipeingui;wipeduringfactoryreset
'
I:Setting up '/data' as data/media emulated storage.
I:mount -o bind '/data/media' '/sdcard' process ended with RC=0
I:mount -o bind '/data/media/0' '/sdcard' process ended with RC=0
I:mount -o bind '/data/media/0' '/sdcard' process ended with RC=0
I:Processing '/external_sd'
I:Processing '/usbotg'
I:Backup folder set to '/data/media/0/TWRP/BACKUPS/0123456789ABCDEF'
I:Settings storage is '/data/media/0'
I:Decrypt adopted storage starting
I:PageManager::LoadFileToBuffer loading filename: '/data/system/storage.xml' directly
Updating partition details...
I:Data backup size is 849MB, free: 11865MB.
I:Unable to mount '/usbotg'
I:Actual block device: '', current file system: 'auto'
...done
I:Unmounting main partitions...


Partition Logs:
/boot | /dev/block/mmcblk0p7 | Size: 16MB
   Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p7
   Display_Name: Boot
   Storage_Name: Boot
   Backup_Path: /boot
   Backup_Name: boot
   Backup_Display_Name: Boot
   Storage_Path: /boot
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/logo | /dev/block/mmcblk0p11 | Size: 8MB
   Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p11
   Display_Name: Logo
   Storage_Name: Logo
   Backup_Path: /logo
   Backup_Name: logo
   Backup_Display_Name: Logo
   Storage_Path: /logo
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/nvram | /dev/block/mmcblk0p2 | Size: 5MB
   Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p2
   Display_Name: Nvram
   Storage_Name: Nvram
   Backup_Path: /nvram
   Backup_Name: nvram
   Backup_Display_Name: Nvram
   Storage_Path: /nvram
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/recovery | /dev/block/mmcblk0p8 | Size: 16MB
   Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p8
   Display_Name: Recovery
   Storage_Name: Recovery
   Backup_Path: /recovery
   Backup_Name: recovery
   Backup_Display_Name: Recovery
   Storage_Path: /recovery
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/lk | /dev/block/mmcblk0p6 | Size: 0MB
   Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p6
   Display_Name: Uboot
   Storage_Name: Uboot
   Backup_Path: /lk
   Backup_Name: lk
   Backup_Display_Name: Uboot
   Storage_Path: /lk
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/proinfo | /dev/block/mmcblk0p1 | Size: 3MB
   Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p1
   Display_Name: Proinfo
   Storage_Name: Proinfo
   Backup_Path: /proinfo
   Backup_Name: proinfo
   Backup_Display_Name: Proinfo
   Storage_Path: /proinfo
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/protect_f | /dev/block/mmcblk0p3 | Size: 4MB Used: 0MB Free: 4MB Backup Size: 0MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Has_SubPartition IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p3
   Display_Name: Protect
   Storage_Name: Protect
   Backup_Path: /protect_f
   Backup_Name: protect_f
   Backup_Display_Name: Protect
   Storage_Path: /protect_f
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/protect_s | /dev/block/mmcblk0p4 | Size: 4MB Used: 0MB Free: 4MB Backup Size: 0MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Is_SubPartition IsPresent 
   SubPartition_Of: /protect_f
   Primary_Block_Device: /dev/block/mmcblk0p4
   Display_Name: protect_s
   Storage_Name: protect_s
   Backup_Path: /protect_s
   Backup_Name: protect_s
   Backup_Display_Name: protect_s
   Storage_Path: /protect_s
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/system | /dev/block/mmcblk0p16 | Size: 1518MB Used: 1498MB Free: 20MB Backup Size: 1498MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_Available_in_GUI IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p16
   Display_Name: System
   Storage_Name: System
   Backup_Path: /system
   Backup_Name: system
   Backup_Display_Name: System
   Storage_Path: /system
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/system_image | /dev/block/mmcblk0p16 | Size: 1568MB
   Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p16
   Display_Name: System
   Storage_Name: System
   Backup_Path: /system_image
   Backup_Name: system_image
   Backup_Display_Name: System
   Storage_Path: /system_image
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/cache | /dev/block/mmcblk0p17 | Size: 106MB Used: 0MB Free: 106MB Backup Size: 0MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p17
   Display_Name: Cache
   Storage_Name: Cache
   Backup_Path: /cache
   Backup_Name: cache
   Backup_Display_Name: Cache
   Storage_Path: /cache
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/data | /dev/block/mmcblk0p18 | Size: 12751MB Used: 849MB Free: 11865MB Backup Size: 849MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent Can_Be_Encrypted Has_Data_Media Can_Encrypt_Backup Use_Userdata_Encryption Is_Storage Is_Settings_Storage 
   Symlink_Path: /data/media/0
   Symlink_Mount_Point: /sdcard
   Primary_Block_Device: /dev/block/mmcblk0p18
   Display_Name: Data
   Storage_Name: Internal Storage
   Backup_Path: /data
   Backup_Name: data
   Backup_Display_Name: Data
   Storage_Path: /data/media/0
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files
   MTP_Storage_ID: 65537

/external_sd | /dev/block/mmcblk1p1 | Size: 30605MB Used: 14453MB Free: 16152MB Backup Size: 14453MB
   Flags: Can_Be_Mounted Can_Be_Wiped Wipe_Available_in_GUI Removable IsPresent Is_Storage 
   Primary_Block_Device: /dev/block/mmcblk1p1
   Alternate_Block_Device: /dev/block/mmcblk1
   Display_Name: External SD-card
   Storage_Name: External SD-card
   Backup_Path: /external_sd
   Backup_Name: external_sd
   Backup_Display_Name: External SD-card
   Storage_Path: /external_sd
   Current_File_System: vfat
   Fstab_File_System: auto
   Backup_Method: files
   MTP_Storage_ID: 65538

/usbotg |  | Size: 0MB Used: 0MB Free: 0MB Backup Size: 0MB
   Flags: Can_Be_Mounted Can_Be_Wiped Wipe_Available_in_GUI Removable Is_Storage 
   Primary_Block_Device: /dev/block/sda1
   Alternate_Block_Device: /dev/block/sda
   Display_Name: USB-OTG
   Storage_Name: USB-OTG
   Backup_Path: /usbotg
   Backup_Name: usbotg
   Backup_Display_Name: USB-OTG
   Storage_Path: /usbotg
   Current_File_System: auto
   Fstab_File_System: auto
   Backup_Method: files
   MTP_Storage_ID: 65539

I:Loading package: TWRP (/data/media/0/TWRP/theme/ui.zip)
I:Loading zip theme
I:Loading package: TWRP (/twres/ui.xml)
I:Load XML directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/uk.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/tr.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sv.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sl.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sk.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/ru.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/pt_BR.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/pl.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/nl.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/it.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/hu.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/fr.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/es.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/el.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/de.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/cz.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
parsing languageFile
parsing languageFile done
I:PageManager::LoadFileToBuffer loading filename: '/twres/ui.xml' directly
I:Checking resolution...
I:Loading resources...
I:Failed to load image from indeterminate013, error -1
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Including file: /twres/portrait.xml...
I:PageManager::LoadFileToBuffer loading filename: '/twres/portrait.xml' directly
I:Loading resources...
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Loading page main
I:Loading page main2
I:Loading page install
I:Loading page flash_confirm
I:Loading page flash_zip
I:Loading page flash_done
I:Loading page flashimage_confirm
I:Loading page clear_vars
I:Loading page confirm_action
I:Loading page action_page
I:Loading page singleaction_page
I:Loading page action_complete
I:Loading page filecheck
I:Loading page rebootcheck
I:Loading page wipe
I:Loading page advancedwipe
I:Loading page formatdata
I:Loading page formatdata_confirm
I:Loading page checkpartitionlist
I:Loading page partitionoptions
I:Loading page refreshfilesystem
I:Loading page selectfilesystem
I:Loading page backup
I:Loading page backup_options
I:Loading page backupname1
I:Loading page backupname2
I:Loading page backupencryption
I:Loading page backupencryption2
I:Loading page checkbackuppassword
I:Loading page backup_run
I:Loading page restore
I:Unable to open '/data/media/0/TWRP/BACKUPS/0123456789ABCDEF'
I:Loading page restore_read
I:Loading page restore_decrypt
I:Loading page try_restore_decrypt
I:Loading page restore_select
I:Loading page renamebackup
I:Loading page restore_run
I:Loading page mount
I:Loading page usb_mount
I:Loading page usb_umount
I:Loading page system_readonly_check
I:Loading page reboot
I:Loading page system_readonly
I:Loading page settings
I:Loading page settings_timezone
I:Loading page settings_screen
I:Loading page settings_vibration
I:Loading page settings_language
I:Loading page advanced
I:Loading page partsdcardsel
I:Loading page partsdcardcheck
I:Loading page partsdcard
I:Loading page htcdumlock
I:Loading page lock
I:Loading page filemanagerlist
I:Loading page filemanageroptions
I:Loading page choosedestinationfolder
I:Loading page filemanagerrenamefile
I:Loading page filemanagerrenamefolder
I:Loading page filemanagerchmod
I:Loading page filemanagerconfirm
I:Loading page filemanageraction
I:Loading page decrypt
I:Loading page decrypt_pattern
I:Loading page trydecrypt
I:Loading page terminalcommand
I:Loading page sideload
I:Loading page fixcontexts
I:Loading page installsu
I:Loading page slideout
I:Loading page select_storage
I:Loading page select_language
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Switching packages (TWRP)
SELinux contexts loaded from /file_contexts
Full SELinux support is present.
I:Not using /misc, not defined in fstab.
I:Not using /misc, not defined in fstab.
Startup Commands: 
ro.adb.secure=0
ro.cip.partition.support=no
ro.boot.selinux=permissive
ro.boot.hardware=mt6752
ro.boot.serialno=0123456789ABCDEF
ro.boot.bootreason=power_key
ro.omni.device=mtk
ro.twrp.boot=1
ro.twrp.version=3.0.2-1
ro.allow.mock.location=1
ro.board.platform=MT6752
ro.build.id=LMY48B
ro.build.display.id=omni_MTK-eng 5.1.1 LMY47X 1 test-keys
ro.build.product=h560
ro.build.version.sdk=22
ro.mount.fs=EXT4
ro.dalvik.vm.native.bridge=0
ro.secure=0
ro.zygote=zygote32
ro.persist.partition.support=no
ro.product.name=full h560
ro.product.board=
ro.product.brand=alps
ro.product.model=h560
ro.product.device=h560
ro.product.manufacturer=alps
ro.baseband=unknown
ro.bootmode=unknown
ro.hardware=mt6752
ro.revision=0
ro.serialno=0123456789ABCDEF
ro.bootloader=unknown
ro.debuggable=1
ro.factorytest=0
sys.usb.ffs.ready=1
init.svc.adbd=running
init.svc.healthd=running
init.svc.ueventd=running
init.svc.recovery=running
init.svc.set_permissive=stopped
twrp.crash_counter=0
twrp.action_complete=0
dalvik.vm.dex2oat-Xms=64m
dalvik.vm.dex2oat-Xmx=512m
dalvik.vm.image-dex2oat-Xms=64m
dalvik.vm.image-dex2oat-Xmx=64m
persist.mtk.aee.aed=on
persist.sys.usb.config=adb,mtp
persist.service.acm.enable=0
service.adb.root=1

I:Copying file /cache/recovery/log to /cache/recovery/last_log
tw_get_context got selinux context: u:object_r:media_rw_data_file:s0
I:Got default contexts and file mode for storage files.
I:Attempt to load settings from settings file...
I:InfoManager file '/data/media/0/TWRP/.twrps' not found.
I:Backup folder set to '/data/media/0/TWRP/BACKUPS/0123456789ABCDEF'
I:Copying file /etc/recovery.fstab to /cache/recovery/recovery.fstab
I:Version number saved to '/cache/recovery/.version'
I:Unable to mount '/usbotg'
I:Actual block device: '', current file system: 'auto'
__bionic_open_tzdata: couldn't find any tzdata when looking for CST6CDT,M3.2.0,M11.1.0!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
I:TWFunc::Set_Brightness: Setting brightness control to 162
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
parsing languageFile
parsing languageFile done
I:Translating partition display names
I:Backup folder set to '/data/media/0/TWRP/BACKUPS/0123456789ABCDEF'
I:TWFunc::Fixup_Time: Pre-fix date and time: 2016-08-10--15-51-14
I:TWFunc::Fixup_Time: Setting time offset from file /sys/class/rtc/rtc0/since_epoch
I:TWFunc::Fixup_Time: Date and time corrected: 2016-08-10--15-51-14
I:Enabling MTP during startup
I:Starting MTP
Starting MTP
I:sending message to add 65537 '/data/media/0' 'Internal Storage'
I:Message sent, add storage ID: 65537
I:sending message to add 65538 '/external_sd' 'Micro SDCard'
I:Message sent, add storage ID: 65538
MTP Enabled
I:Switching packages (TWRP)
I:Set page: 'system_readonly'
Using '/dev/mtp_usb' for MTP device.
created new mtpserver object
MtpServer::run fd: 21
mtppipe add storage 65537 '/data/media/0'
MtpStorage id: 65537 path: /data/media/0
mtppipe add storage 65538 '/external_sd'
MtpStorage id: 65538 path: /external_sd
I:Is_Mounted: Unable to find partition for path '/vendor'
I:operation_start: 'Toggle System Mount'
I:operation_end - status=1
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Switching packages (TWRP)
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'advanced'
I:Set page: 'confirm_action'
I:Set page: 'action_page'
I:operation_start: 'Copy Log'
I:Copying file /tmp/recovery.log to /data/media/0/recovery.log

i hope this is your request..
thanks a lot

**Comment by ulefonebt2** [comment]
ops sorry it is not closed...

**Comment by ulefonebt2** [comment]
Rovo any idea??

**Comment by rovo89** [comment]
The log says that there are 20 MB free, that's probably before flashing. I assume that's not enough space.

**Comment by DarkShoken** [comment]
Hi there, I don't know if the problem is resolved, but I have figured days ago how to fix this issue.
- Flash TWRP
- Install SuperSu.zip
- Reboot 
- Download [https://play.google.com/store/apps/details?id=com.jumobile.manager.systemapp&hl=fr](url)
- Remove all bloatwares on your phone
- Reboot on TWRP
- You can now install Xposed Framework.

**Comment by rovo89** [comment]
I think any other way to free up space on `/system` would work as well.

**Comment by edv4r** [comment]
Hello the Xposed does not work on the g530m Lollipop 5.0.2

**Comment by edv4r** [comment]
Hello I have problems with the Xposed, I do not work on the Samsung galaxy Grand prime g530m Lite Lollipop 5.0.2 ???

**Comment by edv4r** [comment]
When finished installing Xposed zip The phone gives me a warning that Google play is deyu   In the galaxy Grand prime g539m Lollipop 5.0.2. :( Please help.

**Comment by noahjutz** [comment]
Are you shure you've downloaded the right build? You need to choose the right cpu (arm, arm64, x86) and the right sdk (sdk21 = Android 5.0; sdk22 = Android 5.1; sdk23 = Android 6.0)

**Comment by gregmorin** [comment]
I have Moto E4
Twrp 3.1.1
Nougat 7.1.1
When I try to flash xposed v88.2 sdk-25 in recovery...it gives me an error saying /data/magisk.img mount failed....updater process ended with ERROR: 1....can anybody plzz help me to solve this....thanks

**Comment by vinhphucng25** [comment]
I have HTC 10 rooted 
TWRP 3.2
Nougat 7.0 
And I have same problem. 😭

**Comment by gregmorin** [comment]
Woah...I thought in the whle world I only had this problem..😁😁😁 hmm did you find any solution for this @vinphucng25....?

**Comment by ibq00** [comment]
重新下载吧！最好用浏览器下载！还有，用读卡器拖拽保存文件，

**Comment by gregmorin** [comment]
Not working...tried redownloading and flashing in recovery...any other trick to solve this...?

**Comment by vinhphucng25** [comment]
@gregmorin I have to wipe all data & system on TWRP and reinstall system first and then Xposed and final is every single app. 😆

**Comment by gregmorin** [comment]
I tried all the all things...wiped system, data, cache....flashed the stock 7.1.1 and then flashed xposed 88.2 still same problem..

**Comment by iamsabbir12** [comment]
same error 1 problem appearing when i try to install nougat 7.1 on my samsung galaxy j200h i cannot figure out how to solve that

**Comment by xstar97** [comment]
@iamsabbir12 check out the this xda link for root....https://www.xda-developers.com/root/

**Comment by ghost** [comment]
Here is a guide to [fix magisk error 1](https://savegyd.com/fix-magisk-install-error/)
