### ISSUE TITLE
How to set xposed hook time when I want to hook plugin

### ISSUE THREAD

**Issue by 3412566455** [rovo89/XposedInstaller#340]
Excuse me. I'm sorry  to ask you some question about how to hook WeChat Plugin,
this is my code:
XposedHelpers.findAndHookMethod("com.tencent.mm.plugin.scanner.ui.BaseScanUI",paramLoadPackageParam.classLoader, "onPreviewFrame",byte[].class,Camera.class, new XC_MethodHook() {
			@Override
			protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
				super.beforeHookedMethod(param);
				XposedBridge.log("参数1 = " + param.args[0]);  
				XposedBridge.log("参数2 = " + param.args[1]);  
			}
		});
but the xposed log is notify not find this class ,I want to ask how to solve this problem

**Comment by someonec** [comment]
Hi there,

Your problem could be solved by two steps.

First let's speak chinese,:)

----------------------我是分割线----------------

首先，你Hook的包名com.tencent.mm.plugin.scanner.ui.BaseScanUI乍一看在Plugin下

那么微信有两个ClassLoader 主程序ClassLoader和Plugin插件程序ClassLoader

你需要在加载的时候吧第二个ClassLoader用全局变量临时存储下来

其次你要Hook的方法需要贴出来，保证类名方法名正确，而不是构造方法，静态方法，内部类等（这些要用其他方式去Hook）

sample code:(to find the ClassLoader)

findAndHookMethod("com.tencent.mm.compatible.util.i", lpparam.classLoader,"b",String.class, ClassLoader.class,new XC_MethodHook() {
				 @Override
			     protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
			    	 XposedBridge.log("bbbbb:damowang classLoader util.i"+param.args[0]+"=="+param.args[1]);
			    	 ClassLoader loader = (ClassLoader)param.args[1];
			    	 cLoader = loader;//plugin classLoader you want
................

anything else please reply to this email or contact ： 594605440@qq.com

cheers,
