### ISSUE TITLE
Activate and reboot button doesn't work

### ISSUE THREAD

**Issue by kulankit97** [rovo89/XposedInstaller#346]
In notifications, while installing modules, activate and reboot button doesn't work in the latest material xposed installer.. please fix the issue..

Xposed installer version 3.1

Any other info needed?

**Comment by rovo89** [comment]
"doesn't work" can mean many things: no reaction at all, error message is shown, module gets activated but reboot fails, device reboots without activating the module before, ...

**Comment by kulankit97** [comment]
Sorry.. I was busy.. problem is module gets activated but reboot fails..

**Comment by rovo89** [comment]
Ok, @DVDAndroid seems to have guessed it. Anyway, please remember to mention such important details the next time you report bugs (here or else where). 3.1.1 is out now with the fix.
