### ISSUE TITLE
Include a compiled apk file in the Github releases

### ISSUE THREAD

**Issue by voidstarstar** [rovo89/XposedInstaller#357]
It may be useful to add the compiled apk file as a binary asset to each release [as described here](https://github.com/blog/1547-release-your-software).

This could make it easier to automate downloading in 3rd party apps such as https://github.com/daktak/xposed_downloader/issues/18.

**Comment by rovo89** [comment]
There are certainly reasons why I could add the APK on GitHub as well, but I prefer to keep it all in one place, that is on XDA, next to other relevant information and release notes. In the future, I'll also move updates to repo.xposed.info again. The reason why I can't do that now: Existing users would get an update notification, even those who are still on Android 4.x which isn't compatible with the newer versions at the moment.

I don't see the need for a 3rd party app to download Xposed by the way. The latest official Xposed Installer let's you download the correct framework ZIPs easily, and downloading+installing a 3rd party app just to download Xposed Installer is kind of pointless.
