### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by dilrajkehra** [rovo89/XposedInstaller#364]
Xposed framework   "de.robv.android.xposed.installer_v32_de4f0d.apk" is not being able to install on my phone
Samsung galaxy core 2 4.4.2 kitkat rooted
The error is
Xposed is not (yet) compatible with Android SDK version 19 or your processor architecture
(armeabi-v7a).

Warning:linker: /data/data/de.robv.android.installer/cache/app _ process has text relocations. This is wasting memory and a security risk.please fix
CANNOT LINK EXECUTABLE: cannot locate symbol
"zn7android14AndroidRuntime5startEPKcS2"
referenced by "/data/data/de.robv.android.installer/cache/app _ process"...

**Comment by rovo89** [comment]
Why two issues??? https://github.com/rovo89/Xposed/issues/204
