### ISSUE TITLE
Xposed 3.1 not Kit-Kat safe?

### ISSUE THREAD

**Issue by Rbagman** [rovo89/XposedInstaller#367]
I noted an Xposed upgrade (2.6.1 ->) available in the F-Droid catalogue this morning; it referenced the ru.meefik Busybox — which I installed.

After installing both apps, I froze the already installed Play Store Busyboxes: Free and Pro (Stephen Erik); after reboot the installer said framework wasn't installed. It also sais there where known issues with the Kit-Kat ROM.

After I unfroze the Play Store 'boxes and reinstalled Xposed 2.6.1 everything is working fine. 

What's  the difference between F-Droid's Busybox and Play Store's (Stephen Erik) Busybox?

[Android 4.4.2 Samsung GT-N7100]

**Comment by rovo89** [comment]
Xposed Installer 3.1 is indeed not compatible with KitKat. The latest version was 2.7, which you can download from the official website repo.xposed.info.

Xposed doesn't depend on any BusyBox app, it comes bundled with its own BusyBox binary.

I can't control what others post somewhere. You should just stick to the official places, that means repo.xposed.info and my XDA threads.
