### ISSUE TITLE
Throw away all the code for updating packages and use F-Droid for that

### ISSUE THREAD

**Issue by KOLANICH** [rovo89/XposedInstaller#369]

**Comment by KOLANICH** [comment]
Could you explain your position?

**Comment by rovo89** [comment]
Could you explain yours?

**Comment by KOLANICH** [comment]
My one is that it is possible to create third-party F-Droid repos which is a common approach for the ones spreading their android apps: at least Tox, Guardian Project and MicroG use it. So I see no reason to have the code for managing packages in XPosed installer anymore as this can be outsourced to F-Droid. This can also allow a better UX since most of the updates will be in a single app and automatic updates. If you are concerned about mixing xposed packages with non-xposed ones you can create a submenu in the app for exposed packages (it is done in xml config the app downloads)

**Comment by rovo89** [comment]
So you would throw away an easy-to-use repository of 1,000 modules which is well integrated into the app and instead ask millions of users to install F-Droid and configure it with some custom repository URL? And that is supposed to be better UX?

**Comment by rovo89** [comment]
By the way, developers could upload their modules to F-Droid or any other place they might prefer. Xposed Installer will happily let you activate the modules, no matter how you have installed it. But saying that there's "no reason" to have a built-in module browser/installer is very far-fetched.

**Comment by KOLANICH** [comment]
1 You can keep the old repo for compatibility with old versions. All you need to do is to setup tls and generate an xml file for fdroid when the repo updates.
2 Your xposed is a powerful thing, right? You can hook something in f-droid app and add there a repo automatically. Or you can use xposed installer's root privileges to add the repo by editing fdroid files in its folder.
3 The better usabiliity is that it has a better UI and auto-update feature. It also has some features missing in xposed installer, such as sharing packages over wifi/bluetooth, installation of them bypassing the confirmation dialogue, beta-versions, permission, antifeature and compatibility indication. It also have a drawback - it is a bit slow on my phone and imho it asks too many permissions, (I have not checked if the source corresponds to binary, I just use the old version and it works fine). I'd prefer to have one package manager on the system than a bunch of different ones imcompatible with each other.
