### ISSUE TITLE
Snapchat detects Xposed

### ISSUE THREAD

**Issue by iamkarlson** [rovo89/XposedInstaller#372]
I hid my Xposed with RootCloak by following words:

- XposedBridge
- XposedBridge.jar

However, SnapChat still detects Xposed and block my login. I aware of #93 and suppose that this issues related. Could you suggest me how to workaround this Xposed behaviour just for Snapchat??

**Comment by rovo89** [comment]
You could try to create a module that hooks `System.getProperty()` inside the Snapchat app and modify the value it returns for `java.class.path`. I would be surprised though if RootCloak doesn't already do that for you.

There are many ways for apps to detect Xposed, and trying to hide these traces would be an endless back-and-forth, so I'm not going to start with that. I also don't think that this is the task of the framework. There are modules and apps for this, like you mentioned. Please check with them for this issue.
