### ISSUE TITLE
SD card install

### ISSUE THREAD

**Issue by dimqua** [rovo89/XposedInstaller#377]
Please allow to install the app to SD card.

**Comment by sd1998** [comment]
@dimqua  Do you prefer SD card or do you wan't that the app should be installed in SD card only when Internal Storage is full?

**Comment by rovo89** [comment]
I think it's technically not possible to allow installation on SD card. AFAIK, those apps store their data somewhere in /mnt, but the other parts of Xposed are expecting it in /data. Besides, the SD card might not be mounted that early during boot. Anyway, if someone wants to give it a try, please let me know about the results.

**Comment by rovo89** [comment]
It turned out that installing on external storage really breaks Xposed, so this can't be enabled.
