### ISSUE TITLE
Installing zip file ERROR 1

### ISSUE THREAD

**Issue by whoislxy** [rovo89/XposedInstaller#380]
when i try install the file 26-07-17-xposed-systemless-v87-sdk25-by-PurifyOS.zip  in recovery

appears this message with error:

Updater process ended with ERROR: 1 
Error installing zip file'/sdcard/6-07-17-xposed-systemless-v87-sdk25-by-PurifyOS.zip'

 TWRP log:

__bionic_open_tzdata: couldn't find any tzdata when looking for localtime!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
Starting TWRP 3.0.2-0 on Fri Sep 29 10:39:47 2017
 (pid 1885)
BOARD_HAS_NO_REAL_SDCARD := true
RECOVERY_SDCARD_ON_DATA := true
I:CPU temperature file '/sys/class/thermal/thermal_zone0/temp' not found, disabling CPU temp.
TW_NO_USB_STORAGE := true
TW_INCLUDE_CRYPTO := true
I:TW_BRIGHTNESS_PATH := /brightness
I:Specified brightness file '/brightness' not found.
I:Found brightness file at '/sys/devices/platform/s5p-dsim.0/ea8061/backlight/panel/brightness'
I:TWFunc::Set_Brightness: Setting brightness control to 255
I:LANG: en
Starting the UI...Skipping adf graphics -- not present in build tree
Skipping drm graphics -- not present in build tree
fb0 reports (possibly inaccurate):
  vi.bits_per_pixel = 32
  vi.red.offset   =  16   .length =   8
  vi.green.offset =   8   .length =   8
  vi.blue.offset  =   0   .length =   8
setting GGL_PIXEL_FORMAT_BGRA_8888
double buffered
framebuffer: 3 (720 x 1280)
Using fbdev graphics.
I:TWFunc::Set_Brightness: Setting brightness control to 255
I:Loading package: splash (/twres/splash.xml)
I:Load XML directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/splash.xml' directly
I:Checking resolution...
I:Scaling theme width 0.666667x and height 0.666667x, offsets x: 0 y: 0
I:Loading resources...
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Loading page splash
I:Switching packages (splash)
=> Linking mtab
=> Processing recovery.fstab
I:Processing '/efs'
I:Created '/efs' folder.
I:Processing '/boot'
I:Processing '/recovery'
I:Processing '/modem'
I:Processing '/cache'
I:Processing '/system'
I:Processing '/data'
I:Setting up '/data' as data/media emulated storage.
I:Created '/sdcard' folder.
I:mount -o bind '/data/media' '/sdcard' process ended with RC=0
I:mount -o bind '/data/media/0' '/sdcard' process ended with RC=0
I:mount -o bind '/data/media/0' '/sdcard' process ended with RC=0
I:Processing '/external_sdcard'
I:Created '/external_sdcard' folder.
I:Processing '/usb-otg'
I:Created '/usb-otg' folder.
I:Backup folder set to '/data/media/0/TWRP/BACKUPS/4df7ef1c2db62115'
I:Settings storage is '/data/media/0'
I:Decrypt adopted storage starting
I:PageManager::LoadFileToBuffer loading filename: '/data/system/storage.xml' directly
I:successfully loaded storage.xml
Updating partition details...
I:Data backup size is 2365MB, free: 6860MB.
I:Unable to mount '/usb-otg'
I:Actual block device: '', current file system: 'vfat'
...done
I:Unmounting main partitions...

Partition Logs:
/efs | /dev/block/mmcblk0p3 | Size: 19MB Used: 9MB Free: 10MB Backup Size: 9MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p3
   Display_Name: EFS
   Storage_Name: EFS
   Backup_Path: /efs
   Backup_Name: efs
   Backup_Display_Name: EFS
   Storage_Path: /efs
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/boot | /dev/block/mmcblk0p8 | Size: 8MB
   Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p8
   Display_Name: Boot
   Storage_Name: Boot
   Backup_Path: /boot
   Backup_Name: boot
   Backup_Display_Name: Boot
   Storage_Path: /boot
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/recovery | /dev/block/mmcblk0p9 | Size: 8MB
   Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p9
   Display_Name: Recovery
   Storage_Name: Recovery
   Backup_Path: /recovery
   Backup_Name: recovery
   Backup_Display_Name: Recovery
   Storage_Path: /recovery
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/modem | /dev/block/mmcblk0p10 | Size: 88MB
   Flags: Can_Be_Backed_Up IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p10
   Display_Name: Modem
   Storage_Name: Modem
   Backup_Path: /modem
   Backup_Name: modem
   Backup_Display_Name: Modem
   Storage_Path: /modem
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/cache | /dev/block/mmcblk0p12 | Size: 1346MB Used: 23MB Free: 1322MB Backup Size: 23MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p12
   Display_Name: Cache
   Storage_Name: Cache
   Backup_Path: /cache
   Backup_Name: cache
   Backup_Display_Name: Cache
   Storage_Path: /cache
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/system | /dev/block/mmcblk0p13 | Size: 1511MB Used: 836MB Free: 675MB Backup Size: 836MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_Available_in_GUI IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p13
   Display_Name: System
   Storage_Name: System
   Backup_Path: /system
   Backup_Name: system
   Backup_Display_Name: System
   Storage_Path: /system
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/data | /dev/block/mmcblk0p16 | Size: 10709MB Used: 2365MB Free: 6860MB Backup Size: 2365MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent Can_Be_Encrypted Has_Data_Media Can_Encrypt_Backup Use_Userdata_Encryption Is_Storage Is_Settings_Storage 
   Symlink_Path: /data/media/0
   Symlink_Mount_Point: /sdcard
   Primary_Block_Device: /dev/block/mmcblk0p16
   Length: -32768
   Display_Name: Data
   Storage_Name: Internal Storage
   Backup_Path: /data
   Backup_Name: data
   Backup_Display_Name: Data
   Storage_Path: /data/media/0
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files
   MTP_Storage_ID: 65537

/external_sdcard | /dev/block/mmcblk1p1 | Size: 7564MB Used: 1909MB Free: 5654MB Backup Size: 1909MB
   Flags: Can_Be_Mounted Can_Be_Wiped Wipe_Available_in_GUI Removable IsPresent Is_Storage 
   Primary_Block_Device: /dev/block/mmcblk1p1
   Alternate_Block_Device: /dev/block/mmcblk1
   Display_Name: External SDCard
   Storage_Name: External SDCard
   Backup_Path: /external_sdcard
   Backup_Name: external_sdcard
   Backup_Display_Name: External SDCard
   Storage_Path: /external_sdcard
   Current_File_System: vfat
   Fstab_File_System: exfat
   Backup_Method: files
   MTP_Storage_ID: 65538

/usb-otg |  | Size: 0MB Used: 0MB Free: 0MB Backup Size: 0MB
   Flags: Can_Be_Mounted Can_Be_Wiped Wipe_Available_in_GUI Removable Is_Storage 
   Primary_Block_Device: /dev/block/sda1
   Alternate_Block_Device: /dev/block/sda
   Display_Name: USB-OTG
   Storage_Name: USB-OTG
   Backup_Path: /usb-otg
   Backup_Name: usb-otg
   Backup_Display_Name: USB-OTG
   Storage_Path: /usb-otg
   Current_File_System: vfat
   Fstab_File_System: vfat
   Backup_Method: files
   MTP_Storage_ID: 65539

I:Loading package: TWRP (/data/media/0/TWRP/theme/ui.zip)
I:Loading zip theme
I:Loading package: TWRP (/twres/ui.xml)
I:Load XML directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/uk.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/tr.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sv.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sl.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sk.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/ru.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/pt_BR.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/pl.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/nl.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/it.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/hu.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/fr.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/es.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/el.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/de.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/cz.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
parsing languageFile
parsing languageFile done
I:PageManager::LoadFileToBuffer loading filename: '/twres/ui.xml' directly
I:Checking resolution...
I:Scaling theme width 0.666667x and height 0.666667x, offsets x: 0 y: 0
I:Loading resources...
I:Failed to load image from indeterminate013, error -1
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Including file: /twres/portrait.xml...
I:PageManager::LoadFileToBuffer loading filename: '/twres/portrait.xml' directly
I:Loading resources...
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Loading page main
I:Loading page main2
I:Loading page install
I:Loading page flash_confirm
I:Loading page flash_zip
I:Loading page flash_done
I:Loading page flashimage_confirm
I:Loading page clear_vars
I:Loading page confirm_action
I:Loading page action_page
I:Loading page singleaction_page
I:Loading page action_complete
I:Loading page filecheck
I:Loading page rebootcheck
I:Loading page wipe
I:Loading page advancedwipe
I:Loading page formatdata
I:Loading page formatdata_confirm
I:Loading page checkpartitionlist
I:Loading page partitionoptions
I:Loading page refreshfilesystem
I:Loading page selectfilesystem
I:Loading page backup
I:Loading page backup_options
I:Loading page backupname1
I:Loading page backupname2
I:Loading page backupencryption
I:Loading page backupencryption2
I:Loading page checkbackuppassword
I:Loading page backup_run
I:Loading page restore
I:Unable to open '/data/media/0/TWRP/BACKUPS/4df7ef1c2db62115'
I:Loading page restore_read
I:Loading page restore_decrypt
I:Loading page try_restore_decrypt
I:Loading page restore_select
I:Loading page renamebackup
I:Loading page restore_run
I:Loading page mount
I:Loading page usb_mount
I:Loading page usb_umount
I:Loading page system_readonly_check
I:Loading page reboot
I:Loading page system_readonly
I:Loading page settings
I:Loading page settings_timezone
I:Loading page settings_screen
I:Loading page settings_vibration
I:Loading page settings_language
I:Loading page advanced
I:Loading page partsdcardsel
I:Loading page partsdcardcheck
I:Loading page partsdcard
I:Loading page htcdumlock
I:Loading page lock
I:Loading page filemanagerlist
I:Loading page filemanageroptions
I:Loading page choosedestinationfolder
I:Loading page filemanagerrenamefile
I:Loading page filemanagerrenamefolder
I:Loading page filemanagerchmod
I:Loading page filemanagerconfirm
I:Loading page filemanageraction
I:Loading page decrypt
I:Loading page decrypt_pattern
I:Loading page trydecrypt
I:Loading page terminalcommand
I:Loading page sideload
I:Loading page fixcontexts
I:Loading page installsu
I:Loading page slideout
I:Loading page select_storage
I:Loading page select_language
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Switching packages (TWRP)
Renaming regular /file_contexts -> /file_contexts.bak
Moving /prebuilt_file_contexts -> /file_contexts
SELinux contexts loaded from /file_contexts
Full SELinux support is present.
I:Not using /misc, not defined in fstab.
I:Not using /misc, not defined in fstab.
Startup Commands: 
ro.sf.lcd_density=320
ro.adb.qemud=1
ro.com.google.gmsversion=4.1_r2
ro.com.google.clientidbase=android-samsung
ro.com.android.dateformat=MM-dd-yyyy
ro.com.android.dataroaming=true
ro.ril.hsxpa=1
ro.ril.gprsclass=10
ro.sec.fle.encryption=true
ro.boot.emmc=0
ro.boot.sec_atd.tty=/dev/ttySAC2
ro.boot.selinux=enforcing
ro.boot.serialno=4df7ef1c2db62115
ro.boot.bootloader=N7100ZSUFNL1
ro.boot.debug_level=0x4f4c
ro.boot.warranty_bit=1
ro.boot.emmc_checksum=3
ro.boot.odin_download=1
ro.emmc=0
ro.omni.device=t03g
ro.twrp.boot=1
ro.twrp.version=3.0.2-0
ro.wifi.channels=
ro.allow.mock.location=1
ro.board.platform=exynos4
ro.build.id=KTU84P
ro.build.PDA=N7100XXALI3
ro.build.date=Tue Apr  5 02:56:52 EDT 2016
ro.build.date.utc=0
ro.build.host=build
ro.build.tags=test-keys
ro.build.type=eng
ro.build.user=jenkins
ro.build.display.id=omni_t03g-eng 4.4.4 KTU84P 18 test-keys
ro.build.product=t03g
ro.build.version.sdk=19
ro.build.version.release=4.4.4
ro.build.version.codename=REL
ro.build.version.incremental=18
ro.build.changelist=121996
ro.build.hidden_ver=N7100XXALI3
ro.build.description=omni_t03g-eng 4.4.4 KTU84P 18 test-keys
ro.build.fingerprint=Samsung/omni_t03g/t03g:4.4.4/KTU84P/18:eng/test-keys
ro.build.characteristics=default
ro.error.receiver.default=com.samsung.receiver.error
ro.hdcp2.rx=tz
ro.tvout.enable=true
ro.config.ringtone=S_Over_the_horizon.ogg
ro.config.alarm_alert=Walk_in_the_forest.ogg
ro.config.media_sound=Media_preview_Touch_the_light.ogg
ro.config.notification_sound=S_Whistle.ogg
ro.kernel.qemu=0
ro.kernel.android.checkjni=1
ro.secure=0
ro.secwvk=220
ro.carrier=unknown
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.name=omni_t03g
ro.product.board=smdk4x12
ro.product.brand=Samsung
ro.product.model=t03g
ro.product.device=t03g
ro.product.locale.region=US
ro.product.locale.language=en
ro.product.manufacturer=Samsung
ro.baseband=unknown
ro.bootmode=unknown
ro.hardware=smdk4x12
ro.opengles.version=131072
ro.revision=11
ro.serialno=4df7ef1c2db62115
ro.bootloader=N7100ZSUFNL1
ro.debuggable=1
ro.factorytest=0
ro.product_ship=false
ro.lcd_min_brightness=20
net.bt.name=Android
net.change=net.bt.name
net.streaming.rtsp.uaprof=http://wap.samsungmobile.com/uaprof/
init.svc.adbd=running
init.svc.healthd=running
init.svc.ueventd=running
init.svc.recovery=running
init.svc.set_permissive=stopped
rild.libargs=-d /dev/ttyS0
rild.libpath=/system/lib/libsec-ril.so
twrp.crash_counter=0
twrp.action_complete=0
debug.hwui.render_dirty_regions=false
media.enable-commonsource=true
dalvik.vm.heapsize=256m
dalvik.vm.dexopt-flags=m=y
dalvik.vm.heapstartsize=8m
dalvik.vm.heapgrowthlimit=64m
dalvik.vm.stack-trace-file=/data/anr/traces.txt
persist.log.seclevel=1
persist.sys.usb.config=mtp
persist.sys.dalvik.vm.lib=libdvm.so
persist.sys.storage_preload=1
persist.radio.adb_log_on=1
service.adb.root=1
keyguard.no_require_sim=true

Running boot script...
I:/sbin/runatboot.sh process ended with RC=0
Done.
I:Copying file /cache/recovery/log to /cache/recovery/last_log
tw_get_context got selinux context: u:object_r:media_rw_data_file:s0
I:Got default contexts and file mode for storage files.
I:Attempt to load settings from settings file...
I:InfoManager loading from '/data/media/0/TWRP/.twrps'.
I:Backup folder set to '/data/media/0/TWRP/BACKUPS/4df7ef1c2db62115'
I:Copying file /etc/recovery.fstab to /cache/recovery/recovery.fstab
I:Version number saved to '/cache/recovery/.version'
I:Unable to mount '/usb-otg'
I:Actual block device: '', current file system: 'vfat'
__bionic_open_tzdata: couldn't find any tzdata when looking for CST6CDT,M3.2.0,M11.1.0!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
I:TWFunc::Set_Brightness: Setting brightness control to 255
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
parsing languageFile
parsing languageFile done
I:Translating partition display names
I:Backup folder set to '/data/media/0/TWRP/BACKUPS/4df7ef1c2db62115'
I:Enabling MTP during startup
I:Starting MTP
I:sending message to add 65537 '/data/media/0' 'Internal Storage'
Starting MTP
I:Message sent, add storage ID: 65537
I:sending message to add 65538 '/external_sdcard' 'Micro SDCard'
I:Message sent, add storage ID: 65538
MTP Enabled
I:Check_Lifetime_Writes result: '240120'
I:Switching packages (TWRP)
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
created new mtpserver object
MtpServer::run fd: 25
mtppipe add storage 65537 '/data/media/0'
MtpStorage id: 65537 path: /data/media/0
mtppipe add storage 65538 '/external_sdcard'
MtpStorage id: 65538 path: /external_sdcard
I:Set page: 'install'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'install'
I:Set page: 'flash_confirm'
I:Set page: 'flash_zip'
I:operation_start: 'Flashing'
Installing zip file '/sdcard/26-07-17-xposed-v87-sdk25-Xposed.zip'
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
I:Zip does not contain SELinux file_contexts file in its root.
I:Legacy property environment initialized.
Archive:  /sdcard/26-07-17-xposed-v87-sdk25-Xposed.zip
unzip: zip flags 1 and 8 are not supported
******************************
Xposed framework installer zip
******************************
! Failed: Unable to extract zip file!
Updater process ended with ERROR: 1
I:Legacy property environment disabled.
Error installing zip file '/sdcard/26-07-17-xposed-v87-sdk25-Xposed.zip'
Updating partition details...
I:Data backup size is 2365MB, free: 6845MB.
I:Unable to mount '/usb-otg'
I:Actual block device: '', current file system: 'vfat'
...done
I:Set page: 'flash_done'
I:operation_end - status=1
I:Set page: 'clear_vars'
I:Set page: 'install'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'advanced'
I:Set page: 'confirm_action'
I:Set page: 'action_page'
I:operation_start: 'Copy Log'
I:Copying file /tmp/recovery.log to /data/media/0/recovery.log

 any idea??

**Comment by rovo89** [comment]
As the ZIP file name already says, that's an unofficial version of Xposed. I can't give support for those.
