### ISSUE TITLE
Old Installer Info Within the Installer... 

### ISSUE THREAD

**Issue by ibuprophen1** [rovo89/XposedInstaller#410]
This is a minor item @rovo89 but, the attached image reflects a much older version of the Installer and I was just wondering if you had realized this and if you had any plans for the information to be updated. 

Thank you very much for your time, support and understanding! 

[screenshot_20171113-121747](https://user-images.githubusercontent.com/18060271/32740455-0367ec12-c871-11e7-8f29-476e2d9a0a11.jpg)

**Comment by Ibuprophen** [comment]
Closing this issue since @rovo89 hasn't been very much active (if at all) with XPosed in general... Thanks anyways! :-)
