### ISSUE TITLE
Does this project support the Android 4.0~4.4？

### ISSUE THREAD

**Issue by MHuangXin** [rovo89/XposedInstaller#416]
I  built apk( installler 3.14)  with this project  and  run on android4.4. Error info is can't find a matching zip。
but when i install installer2.7 .i can success to download zip and install Xposed framework 。Now i need to make a System ROM that contain Xposed Framework.so i need  the source code of installer2.7.

**Comment by rovo89** [comment]
No. I don't want to close all doors yet, meaning there might be a version in the future which which supports older Android versions, but currently they're not supported.

Older versions are available via Git tags.

**Comment by MHuangXin** [comment]
I switch tag to 2.7-experimental1.Cannot find android.os.FileUtils.how to slow this problem

**Comment by rovo89** [comment]
It's included in https://github.com/rovo89/XposedInstaller/blob/2.7-experimental1/lib/AndroidHiddenAPI.jar
That tag should build fine with Eclipse. I can't support you in converting it to other build systems, sorry.
