### ISSUE TITLE
Pixel xl2 8.1 Jan log & ss

### ISSUE THREAD

**Issue by sjholland** [rovo89/XposedInstaller#418]
Thank you, I hope this might can help. It said in TWRP "couldn't mount system and vendor" even when manually mounted. Here is log & screenshot after using app to install framework. The second screenshot is after opening app again(log is the same); but after reboot it goes back to not installed like originally.
Cannot read log/data/user_de/0/de.robv.android.xposed.installer/log/error.log (No such file or directory)
![screenshot_20180108-193658](https://user-images.githubusercontent.com/10209448/34701725-620cb634-f4af-11e7-934e-00b63923b884.png)
![screenshot_20180108-200627](https://user-images.githubusercontent.com/10209448/34701761-9b32f39c-f4af-11e7-947f-555100d14c65.png)

Thank you sincerely.

**Comment by rovo89** [comment]
No idea why this error occurs, do you maybe have some Magisk modules activated which block that file? Anyway, v90-beta2 is flashable on TWRP for Pixel devices as well. If there's still an issue with that, please reopen.
