### ISSUE TITLE
/system/framework readonly pixel 2 xl v90 beta 1

### ISSUE THREAD

**Issue by bggold** [rovo89/XposedInstaller#419]
Tried to install v90 on my pixel 2 xl within the xposed app and I get the following error.

cp can't create "/system/framework/xposedbridge.jar": read-only file system
error 1 occurred.

There is no error when it says mounting /system and /vendor read-write

There is nothing in the logs.

If you need a pixel 2 xl to test with let me know I have a spare that I use to test with.

Thanks

**Comment by rovo89** [comment]
Which root app do you use?

**Comment by bggold** [comment]
Magisk v15.2 and the modded manager to not patch dbto

Thanks

**Comment by rovo89** [comment]
Could you please try v90-beta2 and the Xposed Installer 3.1.5?

**Comment by bggold** [comment]
I ended up using the magisk module to install v90.

Thank you

**Comment by rovo89** [comment]
OK, fine, I'll close this issue then.
