### ISSUE TITLE
Xposed Installer on Emulator dosn't work

### ISSUE THREAD

**Issue by tangxuesong6** [rovo89/XposedInstaller#462]
I want to user Xpoed on my emulator(x86),and I have root.But when I install XposedInstaller 3.1.5,it warn 
me that  "Make sure your devide is rooted properly and you have not blocked shell commands".So please 
how to use it on emulator? thanks

**Comment by darkyuhoo01** [comment]
me that "Make sure your devide is rooted properly and you have not blocked shell commands".So please
how to use it on emulator? thanks

**Comment by tangxuesong6** [comment]
已解决

**Comment by 1213766282** [comment]
怎么解决的？
